name: Feature Request
description: template for missing feature
title: '[Feature Request]: '
labels:
  - enhancement
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the problem or missing capability.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed Solution / Enhancement
      description: If you have a solution or feature in mind, please describe it.
