from typing import Literal

type AreaName = Literal[
    "Bob-omb Battlefield",
    "Whomp's Fortress",
    "Jolly Roger Bay",
    "Cool, Cool Mountain",
    "Big Boo's Haunt",
    "Hazy Maze Cave",
    "Lethal Lava Land",
    "Shifting Sand Land",
    "Dire, Dire Docks",
    "Snowman's Land",
    "Wet-Dry World",
    "Tall, Tall Mountain",
    "Tiny-Huge Island",
    "Tick Tock Clock",
    "Rainbow Ride",
    "Bowser in the Dark World",
    "Bowser in the Fire Sea",
    "Bowser in the Sky",
    "Tower of the Wing Cap",
    "Cavern of the Metal Cap",
    "Vanish Cap under the Moat",
    "Princess's Secret Slide",
    "Secret Aquarium",
    "Wing Mario over the Rainbow",
    "Princess Peach's Castle",
]

type EntranceName = Literal[
    "Bob-omb Battlefield",
    "Whomp's Fortress",
    "Jolly Roger Bay",
    "Cool, Cool Mountain",
    "Big Boo's Haunt",
    "Hazy Maze Cave",
    "Lethal Lava Land",
    "Shifting Sand Land",
    "Dire, Dire Docks",
    "Snowman's Land",
    "Wet-Dry World",
    "Tall, Tall Mountain",
    "Tiny-Huge Island (Tiny)",
    "Tiny-Huge Island (Huge)",
    "Tick Tock Clock",
    "Rainbow Ride",
    "Bowser in the Dark World",
    "Bowser in the Fire Sea",
    "Bowser in the Sky",
    "Tower of the Wing Cap",
    "Cavern of the Metal Cap",
    "Vanish Cap under the Moat",
    "Princess's Secret Slide",
    "Secret Aquarium",
    "Wing Mario over the Rainbow",
]
